gomintapa/lib/src/app.dart, gomintapa/lib/src/screens/login.dart, gomintapa/lib/src/screens/register.dart, gomintapa/lib/src/widgets/themes/auth_theme.dart
=> 회원가입 화면 구성

gomintapa_server/package.json
=> feat: 서버 폴더 만들기 및 초기설정

.gitattribute
리포지토리에 언어 .dart랑 .js만 인식하도록 수정했습니당
.gitattribute : 리포지토리에 특정 규칙 및 설정을 적용하기 위해 사용되는 파일
=> .gitattribute 파일을 추가하여 리포지토리 언어 설정

.gitattribute
=> Revert ".gitattributes 파일을 추가하여 리포지토리 언어 설정"

.gitattributes
=> setting: .gitattributes 파일 추가 및 언어 설정

gomintapa/lib/src/screens/home.dart, gomintapa/lib/src/widgets/navigation/back_app_bar.dart, gomintapa/lib/src/widgets/navigation/form_action_app_bar.dart, gomintapa/lib/src/widgets/navigation/home_app_bar.dart, gomintapa/lib/src/widgets/sections/app_bar_section.dart
- home_app_bar.dart 파일
- search_rounded, account_box_rounded 아이콘
- back_app_bar.dart 파일
- arrow_back_rounded 아이콘
- form_action_app_bar.dart 파일
- close_rounded, done_rounded 아이콘
=> refactor: 상단바 재사용

gomintapa/lib/src/screens/my/mypage.dart, gomintapa/lib/src/widgets/sections/my/concern_feed_section.dart, gomintapa/lib/src/widgets/sections/my/concern_tab_bar.dart, gomintapa/lib/src/widgets/sections/my/concern_tab_bar_view.dart
TabBar와 TabBarView 분리 완료
close #29
=> refactor : 마이페이지 화면

gomintapa/lib/src/screens/feed/feed_index.dart, gomintapa/lib/src/widgets/buttons/filter_sheet_button.dart, gomintapa/lib/src/widgets/sections/filter_bar_section.dart, gomintapa/lib/src/widgets/sections/filter_sheet.dart
- 키워드 버튼 클릭 시 필터 section에 나타나고 x 버튼으로 삭제도 가능
=> feat: 선택한 키워드 표시

gomintapa/lib/src/widgets/navigation/back_app_bar.dart, gomintapa/lib/src/widgets/navigation/home_app_bar.dart
- 뒤로가기 버튼 클릭 -> 현재 화면 닫고 이전 화면으로 이동
- 계정 버튼 클릭 -> 마이페이지 화면으로 이동
=> feat: 버튼 클릭시 페이지 이동 기능 구현

gomintapa/lib/src/app.dart, gomintapa/lib/src/screens/feed/feed_index.dart, gomintapa/lib/src/widgets/listitems/concern_list_item.dart
- 사다리꼴 만드는 건 성공했는데 refactor 하면서 코드 분리하고 간격 조정 더 시도할 예정
- 제목과 선택지 내용 모두 텍스트 영역 초과 시 말줄임표 설정
- 카드 누르면 페이지 이동하는 거 보려고 마이페이지로 설정해뒀으니까 혹시라도 누르고 당황하지 마세용
=> UI: 고민 카드 디자인

gomintapa/lib/src/app.dart, gomintapa/lib/src/screens/feed/mak_feed_index.dart, gomintapa/lib/src/screens/feed/tang_feed_index.dart, gomintapa/lib/src/screens/home.dart, gomintapa/lib/src/widgets/listitems/concern_list_item.dart, gomintapa/lib/src/widgets/listitems/mak_list_item.dart, gomintapa/lib/src/widgets/listitems/tang_list_item.dart, gomintapa/lib/src/widgets/texts/custom_text.dart
- 해결탕탕 고민 카드 디자인
- 막상막하 고민 카드 디자인
- 홈화면 고민 카드 디자인
=> UI: 고민 카드 추가 디자인

gomintapa/lib/src/app.dart, gomintapa/lib/src/screens/my/mypage.dart, gomintapa/lib/src/screens/post/create_post.dart, gomintapa/lib/src/widgets/buttons/keyword_select_button.dart, gomintapa/lib/src/widgets/sections/my/bottom_section.dart
=> refactor: 키워드 선택 섹션 분리

gomintapa/lib/src/app.dart, gomintapa/lib/src/screens/feed/tang_feed_index.dart, gomintapa/lib/src/widgets/listitems/tang_list_item.dart
- TangFeedIndex에서 TangListItem을 생성할 때 isOption1Winner와 isOption2Winner boolean 값을 전달함
- 각각의 값에 따라 선택 항목 영역과 고민 카드 배경 색상이 변경됨
=> Feat: 해결탕탕 컬러 변경 기능 구현

gomintapa/lib/src/controllers/feed_controller.dart, gomintapa/lib/src/models/feed_model.dart, gomintapa/lib/src/models/user_model.dart, gomintapa/lib/src/providers/feed_provider.dart, gomintapa/lib/src/screens/feed/feed_index.dart, gomintapa/lib/src/screens/post/create_post.dart, gomintapa/lib/src/screens/shared/global.dart, gomintapa/lib/src/utils/post_submission_util.dart, gomintapa/lib/src/widgets/listitems/concern_list_item.dart, gomintapa/lib/src/widgets/listitems/user_list_item.dart
=> feat: 게시글 작성 기능 완료

gomintapa/lib/src/screens/auth/login.dart, gomintapa/lib/src/screens/auth/register.dart, gomintapa/lib/src/widgets/forms/label_textfield.dart
TextInputType.phone -> TextInputType.text 으로 변경
=> feat: TextField의 keyboardType 변경

gomintapa/lib/src/app.dart, gomintapa/lib/src/screens/feed/feed_index.dart, gomintapa/lib/src/widgets/listitems/concern_list_item.dart
=> feat: 상세페이지 구현 화면 연결 완료

gomintapa/lib/src/controllers/auth_controller.dart, gomintapa/lib/src/providers/provider.dart
=> bug: 앱 재시작 시 로그인 안하도록 고침

gomintapa/lib/src/app.dart
=> comment: app.dart 파일 초기 경로 원래대로 수정

gomintapa/lib/src/providers/feed_provider.dart, gomintapa/lib/src/screens/auth/login.dart, gomintapa/lib/src/screens/my/mypage.dart
=> feat: 로그아웃 기능 완료

.vscode/launch.json, gomintapa/lib/src/screens/post/post_detail.dart, gomintapa/lib/src/widgets/sections/display/choices/choices_section.dart, gomintapa/lib/src/widgets/sections/display/choices/large_text_display.dart
- 임시로 null 값 넣어둠. imagePath가 null이면 아래와 같이 표시됨
=> feat: 이미지 유무에 따른 선택 항목 표시 로직 구현

gomintapa/lib/src/app.dart, gomintapa/lib/src/controllers/user_controller.dart, gomintapa/lib/src/home.dart, gomintapa/lib/src/models/user_model.dart, gomintapa/lib/src/providers/user_provider.dart, gomintapa/lib/src/screens/feed/mak_feed_index.dart, gomintapa/lib/src/screens/feed/tang_feed_index.dart, gomintapa/lib/src/screens/my/mypage.dart, gomintapa/lib/src/screens/my/mypage_edit.dart, gomintapa/lib/src/widgets/sections/my/user_section.dart
=> Feat/80 : 정보수정 기능 완료

gomintapa/lib/src/widgets/forms/input/photo_attachment.dart
PhotoAttachment에서 InkWell로 감싸 터치 가능한 영역으로 변경
=> refactor: PhotoAttachment에서 InkWell로 감싸 터치 가능한 영역으로 변경

gomintapa/lib/src/home.dart, gomintapa/lib/src/screens/feed/feed_index.dart, gomintapa/lib/src/screens/feed/mak_feed_index.dart, gomintapa/lib/src/screens/feed/tang_feed_index.dart, gomintapa/lib/src/widgets/navigation/home_app_bar.dart
=> refactor: 필터바를 home으로 옮겨 중복 코드 없앰

gomintapa/lib/src/screens/post/create_post.dart, gomintapa/lib/src/widgets/forms/input/photo_attachment.dart, gomintapa/linux/flutter/generated_plugin_registrant.cc, gomintapa/linux/flutter/generated_plugins.cmake, gomintapa/macos/Flutter/GeneratedPluginRegistrant.swift, gomintapa/pubspec.lock, gomintapa/pubspec.yaml, gomintapa/windows/flutter/generated_plugin_registrant.cc, gomintapa/windows/flutter/generated_plugins.cmake
고민 작성 화면에서 사진 첨부하기 영역을 누르면 갤러리에서 사진 고를 수 있음
=> feat: PhotoAttachment 위젯에 이미지 선택 기능 구현

gomintapa/lib/src/controllers/feed_controller.dart
=> 투표 에러 메시지 안뜨게 하기

gomintapa/lib/src/screens/post/post_detail.dart, gomintapa/lib/src/widgets/sections/display/choices/choices_section.dart
=> UI: 투표 시 선택한 항목에 효과 구현

gomintapa/lib/src/controllers/feed_controller.dart, gomintapa/lib/src/models/feed_model.dart, gomintapa/lib/src/providers/feed_provider.dart, gomintapa/lib/src/screens/post/create_post.dart, gomintapa/lib/src/screens/post/post_detail.dart
상세페이지에서 선택한 키워드 뜸
근데 조회 기능은 아직...
=> feat: 게시글에 적용한 키워드 뜨게 하기

gomintapa/lib/src/screens/feed/mak_feed_index.dart, gomintapa/lib/src/screens/feed/tang_feed_index.dart, gomintapa/lib/src/widgets/listitems/mak_list_item.dart, gomintapa/lib/src/widgets/listitems/tang_list_item.dart
=> UI: 임시 데이터 삽입
